import { css } from "lit";

export const storefrontStyles = css`
  :host{--red:#e01820;--ink:#090909;--panel:#141414;--line:#2d2d2d;--muted:#999;display:block;direction:rtl;color:#fff;background:var(--ink);font-family:"DIN Next Arabic","Tajawal","Segoe UI",Arial,sans-serif;overflow:hidden}
  *{box-sizing:border-box}button,select,input{font:inherit}a{color:inherit;text-decoration:none}button,a{-webkit-tap-highlight-color:transparent}
  .announcement{min-height:38px;display:flex;align-items:center;justify-content:center;gap:10px;padding:8px 20px;background:linear-gradient(90deg,#8e070d,var(--red),#8e070d);font-size:13px;font-weight:800;text-align:center}.dot{width:7px;height:7px;border-radius:50%;background:#fff;box-shadow:0 0 0 5px #ffffff22}
  .header{position:relative;z-index:5;border-bottom:1px solid #242424;background:#080808fa}.header-main{width:min(1240px,calc(100% - 40px));min-height:88px;margin:auto;display:grid;grid-template-columns:auto minmax(260px,1fr) auto;align-items:center;gap:30px}
  .logo{display:flex;align-items:center;gap:12px;direction:ltr}.mark{position:relative;display:flex;font-size:33px;font-weight:1000;letter-spacing:-3px;line-height:1;transform:skew(-7deg)}.mark .m{color:var(--red);margin:0 2px}.mark:after{content:"";position:absolute;left:-4px;right:-4px;bottom:-8px;height:3px;background:var(--red);transform:skew(25deg)}.logo-copy{display:grid;gap:2px;line-height:1}.logo-copy strong{font-size:13px;letter-spacing:1.4px}.logo-copy small{color:#949494;font-size:9px;letter-spacing:.7px}
  .site-search{position:relative}.site-search input{width:100%;height:48px;border:1px solid #343434;border-radius:4px;padding:0 48px 0 16px;color:#fff;background:#151515;outline:none}.site-search input:focus{border-color:var(--red);box-shadow:0 0 0 3px #e018201d}.site-search svg{position:absolute;right:17px;top:15px;width:19px;stroke:var(--red)}
  .header-actions{display:flex;gap:10px}.icon-button{width:43px;height:43px;display:grid;place-items:center;border:1px solid #303030;border-radius:4px;color:#fff;background:#131313;transition:.2s}.icon-button:hover{border-color:var(--red);color:var(--red);transform:translateY(-2px)}.icon-button svg{width:20px;fill:none;stroke:currentColor;stroke-width:1.8}
  .nav{border-top:1px solid #1d1d1d;background:#0d0d0d}.nav-inner{width:min(1240px,calc(100% - 40px));min-height:50px;margin:auto;display:flex;align-items:center;gap:30px;overflow-x:auto;scrollbar-width:none}.nav-inner::-webkit-scrollbar{display:none}.nav a{flex:none;color:#d7d7d7;font-size:14px;font-weight:800}.nav a:hover,.nav .featured{color:var(--red)}
  .hero{position:relative;min-height:410px;display:flex;align-items:center;isolation:isolate;border-bottom:1px solid #242424;background:radial-gradient(circle at 18% 60%,#e0182037 0,transparent 25%),linear-gradient(100deg,#060606 8%,#101010 51%,#050505 100%)}.hero:before{content:"";position:absolute;inset:0;z-index:-1;opacity:.22;background-image:linear-gradient(120deg,transparent 0 53%,var(--red) 53% 54%,transparent 54% 60%,#fff 60% 60.2%,transparent 60.2%)}.hero:after{content:"PMP";position:absolute;left:-25px;bottom:-48px;z-index:-1;color:transparent;-webkit-text-stroke:1px #ffffff13;font-size:clamp(170px,24vw,360px);font-weight:1000;font-style:italic;letter-spacing:-24px;direction:ltr}.hero-inner{width:min(1240px,calc(100% - 40px));margin:auto;padding:58px 0 78px}.eyebrow{display:inline-flex;align-items:center;gap:9px;font-size:12px;font-weight:900;letter-spacing:.5px}.eyebrow:before{content:"";width:34px;height:3px;background:var(--red)}h1{max-width:760px;margin:17px 0 12px;font-size:clamp(42px,6vw,76px);line-height:.98;letter-spacing:-2.5px}h1 span{color:var(--red)}.hero p{max-width:650px;margin:0;color:#bcbcbc;font-size:17px;line-height:1.8}.hero-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:27px}.button{min-height:49px;padding:0 25px;display:inline-flex;align-items:center;justify-content:center;border:1px solid #333;border-radius:3px;font-weight:900;font-size:14px;transition:.2s}.button.primary{border-color:var(--red);background:var(--red)}.button.primary:hover{background:#ff2029;transform:translateY(-2px)}.button.ghost{background:#ffffff08}.button.ghost:hover{border-color:#fff}
  .finder-wrap{position:relative;z-index:3;width:min(1180px,calc(100% - 40px));margin:-34px auto 0}.finder{border:1px solid #303030;border-top:3px solid var(--red);background:#121212;box-shadow:0 22px 50px #0008}.finder-head{display:flex;align-items:stretch;border-bottom:1px solid #303030}.finder-title{min-width:260px;padding:18px 24px;display:flex;align-items:center;gap:10px;font-size:17px;font-weight:900}.finder-title svg{width:24px;stroke:var(--red);fill:none}.tabs{display:flex;margin-right:auto}.tab{min-width:160px;border:0;border-right:1px solid #292929;color:#aaa;background:transparent;font-weight:900;cursor:pointer}.tab.active{color:#fff;background:var(--red)}.finder-body{padding:20px 24px 24px;display:grid;grid-template-columns:repeat(4,1fr) auto;gap:12px}.finder-body.engine{grid-template-columns:1fr auto}.finder select{width:100%;height:49px;padding:0 13px;border:1px solid #383838;border-radius:3px;color:#e7e7e7;background:#1a1a1a;outline:none}.finder select:focus{border-color:var(--red)}.search-button{min-width:125px;border:0;border-radius:3px;color:#fff;background:var(--red);font-weight:1000;cursor:pointer}.search-button:hover{background:#ff2029}
  .section{width:min(1240px,calc(100% - 40px));margin:auto;padding:72px 0}.section-heading{margin-bottom:28px;display:flex;align-items:end;justify-content:space-between;gap:20px}.section-kicker{margin-bottom:7px;color:var(--red);font-size:12px;font-weight:1000;letter-spacing:.5px}h2{margin:0;font-size:clamp(28px,4vw,42px);line-height:1.1}.view-all{color:#aaa;font-size:13px;font-weight:800;border-bottom:1px solid #555;padding-bottom:4px}.view-all:hover{color:var(--red);border-color:var(--red)}
  .engines{display:grid;grid-template-columns:repeat(6,1fr);gap:11px}.engine-card{position:relative;min-height:178px;padding:23px 18px;display:flex;flex-direction:column;justify-content:flex-end;overflow:hidden;border:1px solid #2b2b2b;background:linear-gradient(145deg,#171717,#0c0c0c);transition:.25s}.engine-card:before{content:attr(data-code);position:absolute;left:-5px;top:5px;color:#ffffff0a;font-size:60px;font-weight:1000;font-style:italic;letter-spacing:-4px;direction:ltr}.engine-card:after{content:"";position:absolute;top:0;right:0;width:3px;height:0;background:var(--red);transition:height .25s}.engine-card:hover{border-color:#4b4b4b;transform:translateY(-5px)}.engine-card:hover:after{height:100%}.engine-code{position:relative;color:var(--red);font-size:26px;font-weight:1000;font-style:italic;direction:ltr;text-align:right}.engine-name{position:relative;margin-top:7px;font-weight:900}.engine-note{position:relative;margin-top:3px;color:#8c8c8c;font-size:11px}
  .parts-section{background:#0d0d0d;border-block:1px solid #202020}.parts{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.part-card{min-height:125px;padding:22px;display:flex;align-items:center;gap:18px;border:1px solid #2b2b2b;background:#141414;transition:.22s}.part-card:hover{border-color:var(--red);background:#181818;transform:translateY(-3px)}.part-icon{width:60px;height:60px;flex:0 0 60px;display:grid;place-items:center;border-radius:50%;color:var(--red);background:#e0182014}.part-icon svg{width:29px;height:29px;fill:none;stroke:currentColor;stroke-width:1.7}.part-title{font-size:17px;font-weight:900}.part-subtitle{margin-top:4px;color:#818181;font-size:11px;direction:ltr;text-align:right}
  .promo{position:relative;min-height:245px;padding:45px;display:flex;align-items:center;overflow:hidden;border:1px solid #343434;background:linear-gradient(110deg,#8f080e 0,#d9161e 42%,#171717 42.2%,#080808 100%)}.promo:after{content:"PERFORMANCE";position:absolute;left:-30px;color:transparent;-webkit-text-stroke:1px #ffffff18;font-size:80px;font-weight:1000;transform:rotate(-7deg);direction:ltr}.promo-copy{position:relative;z-index:1;max-width:490px}.promo-copy strong{display:block;font-size:clamp(28px,4vw,44px);line-height:1.1}.promo-copy p{margin:12px 0 22px;color:#f5d9da;line-height:1.7}.promo .button{color:#111;border-color:#fff;background:#fff}
  .brands{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid #2b2b2b;border-right:1px solid #2b2b2b}.brand{min-height:86px;display:grid;place-items:center;border-left:1px solid #2b2b2b;border-bottom:1px solid #2b2b2b;color:#d5d5d5;font-size:18px;font-weight:1000;direction:ltr;transition:.2s}.brand:hover{color:var(--red);background:#141414}
  .trust{background:#141414;border-top:1px solid #2b2b2b}.trust-inner{width:min(1240px,calc(100% - 40px));margin:auto;display:grid;grid-template-columns:repeat(4,1fr)}.trust-item{min-height:118px;padding:24px;display:flex;align-items:center;justify-content:center;gap:13px;border-left:1px solid #2b2b2b}.trust-item:last-child{border-left:0}.trust-item svg{width:30px;color:var(--red);fill:none;stroke:currentColor;stroke-width:1.7}.trust-item strong{display:block;font-size:14px}.trust-item small{color:#818181;font-size:11px}.footer{padding:36px 20px;color:#8e8e8e;background:#070707;text-align:center;font-size:12px;line-height:1.9}.footer b{color:#d5d5d5}
  @media(max-width:1050px){.engines{grid-template-columns:repeat(3,1fr)}.finder-body{grid-template-columns:repeat(2,1fr)}.search-button{min-height:49px;grid-column:span 2}.header-main{grid-template-columns:auto 1fr}.site-search{grid-row:2;grid-column:1/-1;margin-bottom:16px}.header-actions{margin-right:auto}}
  @media(max-width:720px){.announcement{font-size:11px}.header-main{width:calc(100% - 28px);min-height:72px;gap:15px}.logo-copy{display:none}.mark{font-size:29px}.nav-inner{width:calc(100% - 28px);gap:20px}.nav a{font-size:12px}.hero{min-height:390px}.hero-inner{width:calc(100% - 32px);padding:48px 0 72px}h1{font-size:43px;letter-spacing:-1.8px}.hero p{font-size:14px}.finder-wrap{width:calc(100% - 24px);margin-top:-26px}.finder-head{display:block}.finder-title{min-width:0;padding:15px 17px}.tabs{width:100%}.tab{min-width:0;width:50%;min-height:44px;border-top:1px solid #292929}.finder-body{padding:14px;grid-template-columns:1fr}.search-button{grid-column:auto;min-height:49px}.section{width:calc(100% - 28px);padding:55px 0}.engines{grid-template-columns:repeat(2,1fr);gap:9px}.engine-card{min-height:145px;padding:17px 14px}.engine-code{font-size:22px}.parts{grid-template-columns:1fr}.part-card{min-height:104px}.promo{min-height:300px;padding:28px 22px;background:linear-gradient(145deg,#bb0d14 0,#dd1820 67%,#0b0b0b 67.3%)}.promo:after{font-size:44px;bottom:20px}.brands{grid-template-columns:repeat(2,1fr)}.brand{min-height:72px;font-size:14px}.trust-inner{width:100%;grid-template-columns:repeat(2,1fr)}.trust-item{min-height:100px;padding:15px 10px;border-bottom:1px solid #2b2b2b}.trust-item:nth-child(2){border-left:0}.account{display:none}}
`;
